before_script:
  - echo Starting...
  - whoami
  - groups
after_script:
  - echo Done.
stages:
  - build
build:
  stage: build
  script:
    - cp -R * /var/www/dl.meckl.in/button-game-api
    - cp -R * /var/www/button-game.meckl.in/api
    - chmod 775 /var/www/dl.meckl.in/button-game-api -R
    - chmod 775 /var/www/button-game.meckl.in/api
    - chown www-data:www-data /var/www/dl.meckl.in/button-game-api -R
    - chown www-data:www-data /var/www/button-game.meckl.in/api
