before_script:
  - echo Starting...
  - whoami
  - groups
after_script:
  - echo Done.
stages:
  - build
build:
  stage: build
  script:
    - cp -R * /var/www/dl.meckl.in/button-game-api
    - cp -R * /var/www/button-game.meckl.in/api
    - sudo systemctl restart button-game-api.uwsgi
