before_script:
  - echo Starting...
  - whoami
  - groups
after_script:
  - echo Done.
stages:
  - build
build:
  stage: build
  script:
    - cp -R * [directory]
    - sudo systemctl restart [service name]
